[theme]
primaryColor="#3498db"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8f9fa"
textColor="#2c3e50"
font="sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false 